services:

  # ------------------------------------------------------------
  #                Incoming and outgoing endpoints
  # ------------------------------------------------------------
  veiklos-endpoint:
    container_name: veiklos-endpoint
    image: caddy:2.11.2-alpine
    user: 1000:1000
    read_only: true
    volumes:
      - ./endpoint/Caddyfile:/etc/caddy/Caddyfile:ro
    ports:
      - 80:80
    networks:
      - isolated
      - external
    restart: unless-stopped


  veiklos-exit:
    container_name: veiklos-exit
    image: vuknf/caddy-l4:2.11
    user: 1000:1000
    read_only: true
    volumes:
      - ./exit/Caddyfile:/etc/caddy/Caddyfile:ro
    networks:
      external: {}
      isolated:
        ipv4_address: 172.28.10.15
    restart: unless-stopped
  # ------------------------------------------------------------
  # ------------------------------------------------------------
  # ------------------------------------------------------------









  # ------------------------------------------------------------
  #                     Veiklos system stack
  # ------------------------------------------------------------
  veiklos-vite:
    container_name: veiklos-vite

    # Self-built
    image: veiklos-vite
    build:
      context: ./vite
      dockerfile: Dockerfile                                                         # Prod
      # dockerfile: Dockerfile.dev                                                     # Dev

    # user: 1000:1000
    read_only: true                                                                  # Prod
    # tmpfs:                                                                           # Dev
    #   - /home/node/.npm:uid=1000,gid=1000                                            # Dev
    # volumes:                                                                         # Dev
    #   - ./vite/app:/app                                                              # Dev
    networks:
      - isolated
      # - external                                                                     # Dev
    restart: unless-stopped


  veiklos-db:
    container_name: veiklos-db
    image: postgres:16-alpine
    user: 1000:1000
    read_only: true
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data
    tmpfs:
      - /var/run/postgresql:uid=1000,gid=1000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./_DATA/postgres:/var/lib/postgresql/data
    networks:
      - isolated
    restart: unless-stopped


  veiklos-backend:
    container_name: veiklos-backend

    # Self-built
    image: veiklos-backend
    build: ./backend

    environment:
        PORT: 4000

        # Database
        DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@veiklos-db:5432/${POSTGRES_DB}

        # APP
        SESSION_SECRET: ${SESSION_SECRET}

        # SAML / VU SSO
        IDP_METADATA: /app/certs/vu-idp-metadata.xml
        
        # # Dev SAML
        # SP_ENTITY_ID: https://lab.knf.vu.lt
        # SP_ACS_URL: https://lab.knf.vu.lt/simplesaml/module.php/saml/sp/saml2-acs.php/default-sp

        # Email
        SMTP_HOST: ${SMTP_HOST}
        SMTP_PORT: ${SMTP_PORT}
        SMTP_USER: ${SMTP_USER}
        SMTP_PASS: ${SMTP_PASS}
    volumes:
      - ./_DATA/uploads:/app/uploads
      - ./_SAML:/app/certs:ro
    extra_hosts:
      - "smtp.gmail.com:172.28.10.15"
    networks:
      - isolated
    restart: unless-stopped
  # ------------------------------------------------------------
  # ------------------------------------------------------------
  # ------------------------------------------------------------













networks:
  external:
    external: true
  isolated:
    name: veiklos-isolated
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 172.28.10.0/24
          gateway: 172.28.10.1


