services:

  # ------------------------------------------------------------
  #                Incoming and outgoing endpoints
  # ------------------------------------------------------------
  veiklos-endpoint:
    container_name: veiklos-endpoint
    image: caddy:2.11.2-alpine
    user: 1000:1000
    read_only: true
    volumes:
      - ./endpoint/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./_LOGS/endpoint:/var/log/caddy
    ports:
      - 80:80
    networks:
      - isolated
      - external
    restart: unless-stopped


  veiklos-exit:
    container_name: veiklos-exit
    image: vuknf/caddy-l4:2.11
    user: 1000:1000
    read_only: true
    volumes:
      - ./exit/Caddyfile:/etc/caddy/Caddyfile:ro
    networks:
      external: {}
      isolated:
        ipv4_address: 172.28.10.30
    restart: unless-stopped
  # ------------------------------------------------------------
  # ------------------------------------------------------------
  # ------------------------------------------------------------









  # ------------------------------------------------------------
  #                     Veiklos system stack
  # ------------------------------------------------------------
  veiklos-vite:
    container_name: veiklos-vite

    # Self-built
    image: veiklos-vite
    build:
      context: ./vite
      dockerfile: Dockerfile                                                         # Prod
      # dockerfile: Dockerfile.dev                                                     # Dev

    # user: 1000:1000
    read_only: true                                                                  # Prod
    # tmpfs:                                                                           # Dev
    #   - /home/node/.npm:uid=1000,gid=1000                                            # Dev
    # volumes:                                                                         # Dev
    #   - ./vite/app:/app                                                              # Dev
    networks:
      - isolated
      # - external                                                                     # Dev
    restart: unless-stopped


  veiklos-db:
    container_name: veiklos-db
    image: postgres:16-alpine
    user: 1000:1000
    read_only: true
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data
    tmpfs:
      - /var/run/postgresql:uid=1000,gid=1000
      - /tmp:uid=1000,gid=1000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./_DATA/postgres:/var/lib/postgresql/data
    networks:
      - isolated
    restart: unless-stopped


  veiklos-backend:
    container_name: veiklos-backend

    # Self-built
    image: veiklos-backend
    build: ./backend

    environment:
        PORT: 4000
        LOG_DIR: /app/logs

        # APP
        SESSION_SECRET: ${SESSION_SECRET}
        DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@veiklos-db:5432/${POSTGRES_DB}

        # SAML / VU SSO
        IDP_METADATA: /app/certs/test/idp-metadata.xml
        SP_PRIVATE_KEY_PATH: /app/certs/test/sp-private.key
        SP_CERT_PATH: /app/certs/test/sp-cert.pem
        
        # Email
        MAILJET_APIKEY: ${MAILJET_APIKEY}
        MAILJET_APISECRET: ${MAILJET_APISECRET}
        MAIL_FROM_ADDRESS: noreply@veiklos.knf.vu.lt
    volumes:
      - ./_DATA/uploads:/app/uploads
      - ./_LOGS/backend:/app/logs
      - ./_SAML:/app/certs:ro
    extra_hosts:
      - "in-v3.mailjet.com:172.28.10.30"
    networks:
      - isolated
    restart: unless-stopped
  # ------------------------------------------------------------
  # ------------------------------------------------------------
  # ------------------------------------------------------------













networks:
  external:
    external: true
  isolated:
    name: veiklos-isolated
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 172.28.10.0/24
          gateway: 172.28.10.1


